# Estimate the Estate
## Objective
Your dataset contains property sales for one-family dwellings in Manhattan over the last 12 months, including each property's zip code, building class, square feet, and sale price. However, records have have a sale price of $0 whenever there was a transfer of ownership without a cash consideration (like from parents to children).

Your task is create a new market value column that uses the recorded sale price when available, or estimates it by using the average price per square foot from properties within the same zip code and building class.

[[Source]](https://mavenanalytics.io/data-drills/estimate-the-estate)

In [1]:
import pandas as pd
import numpy as np

file = pd.read_csv("manhattan_property_sales.csv")
file.head(2)

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000

In [ ]:
file = file.assign(
    AVG = lambda d: d["SALE_PRICE"] / d["SQUARE_FEET"],
    SALE_PRICE = lambda d: np.where(
        d["SALE_PRICE"] == 0, 
        d["SQUARE_FEET"] * d["ZIP_CODE"].map(d.groupby("ZIP_CODE")["AVG"].mean()), 
        d["SALE_PRICE"]
    ),
    OVER = lambda d: d["SALE_PRICE"] > 15000000

)

print(f"Total value greater than $15 million: {file['OVER'].sum()}")
file.head(10)

Total value greater than $15 million: 19

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE,tipo_dato,AVG,OVER
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,1.500000e+07,Real,1667.222296,False
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,1.350000e+07,Real,4437.869822,False
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7.650000e+06,Real,2273.402675,False
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,8.718786e+06,Imputado,0.000000,False
4,CHELSEA,344 W 22 STREET,10011,A4,4395,1.310000e+07,Real,2980.659841,False
5,CHELSEA,304 WEST 18TH STREET,10011,A4,3363,4.775000e+06,Real,1419.863217,False
6,CHELSEA,224 WEST 22ND STREET,10011,A9,6715,1.060000e+07,Real,1578.555473,False
7,CHELSEA,217 WEST 20 STREET,10011,A9,7805,1.160000e+07,Real,1486.226778,False
8,GRAMERCY,143 EAST 18 STREET,10003,A4,3360,6.400000e+06,Real,1904.761905,False
9,GRAMERCY,135 EAST 18TH STREET,10003,A4,3192,3.850000e+06,Real,1206.140351,False

In [3]:
file.query("OVER==1")

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE,tipo_dato,AVG,OVER
15,GREENWICH VILLAGE,11 WEST 12TH ST,10011,A4,8125,2.650000e+07,Real,3261.538462,True
16,GREENWICH VILLAGE,152 WEST 13 STREET,10011,A5,3381,1.875000e+07,Real,5545.696539,True
22,GREENWICH VILLAGE,370 WEST 11 STREET,10014,A4,4009,1.999900e+07,Real,4988.525817,True
23,GREENWICH VILLAGE,399 WEST STREET,10014,A4,5498,1.919456e+07,Imputado,0.000000,True
24,GREENWICH VILLAGE,246 WEST 12TH STREET,10014,A4,4104,1.770000e+07,Real,4312.865497,True
25,GREENWICH VILLAGE,230 WEST 11TH STREET,10014,A4,4400,1.999990e+07,Real,4545.431818,True
31,GREENWICH VILLAGE,63 CHARLES STREET,10014,A4,3840,3.335000e+07,Real,8684.895833,True
73,UPPER EAST SIDE,127 EAST 73RD STREET,10021,A4,7978,2.625000e+07,Real,3290.298320,True
74,UPPER EAST SIDE,18 EAST 71 STREET,10021,A4,12060,2.800000e+07,Real,2321.724710,True
83,UPPER EAST SIDE,48 EAST 81 STREET,10028,A4,6200,1.675000e+07,Real,2701.612903,True
87,UPPER EAST SIDE,57 E 66TH STREET,10065,A4,7918,1.919471e+07,Imputado,0.000000,True
92,UPPER EAST SIDE,16 EAST 64TH STREET,10065,A4,6324,2.100000e+07,Real,3320.683112,True
94,UPPER EAST SIDE,10 EAST 67 STREET,10065,A4,9168,3.600000e+07,Real,3926.701571,True
98,UPPER EAST SIDE,8 EAST 62ND STREET,10065,A4,12347,5.500000e+07,Real,4454.523366,True
99,UPPER EAST SIDE,36 EAST 63RD STREET,10065,A7,12882,4.675000e+07,Real,3629.094861,True
100,UPPER EAST SIDE,973 FIFTH AVENUE,10075,A4,13300,4.600000e+07,Real,3458.646617,True
106,UPPER EAST SIDE,61 EAST 80 STREET,10075,A4,6600,1.815000e+07,Real,2750.000000,True
107,UPPER EAST SIDE,4 EAST 80TH STREET,10075,A7,17676,3.800000e+07,Real,2149.807649,True
116,UPPER EAST SIDE,13 EAST 94TH STREET,10128,A4,6420,1.550000e+07,Real,2414.330218,True