# Splitting the Field
## Objective
Your dataset contains the names of all the baseball players from the 2025 MLB season, along with their team(s) and position(s). A player qualifies for a position by starting at least 20 games at that position in the field or 5 games as a pitcher.

Your task is to aggregate this data and return a table counting the number of players at each position, sorted from highest to lowest.

[[Source]](https://mavenanalytics.io/data-drills/splitting-the-field)

In [98]:
import pandas as pd

file = pd.read_csv("baseball_positions.csv")

file.head()

            Name Team Position
0    Aaron Judge  NYY    OF/DH
1    Cal Raleigh  SEA     C/DH
2  Shohei Ohtani  LAD       DH
3      Juan Soto  NYM       OF
4   Tarik Skubal  DET       SP

In [99]:
positions = file["Position"].str.get_dummies("/")
positions.head(5)

   1B  2B  3B  C  DH  OF  RP  SP  SS
0   0   0   0  0   1   1   0   0   0
1   0   0   0  1   1   0   0   0   0
2   0   0   0  0   1   0   0   0   0
3   0   0   0  0   0   1   0   0   0
4   0   0   0  0   0   0   0   1   0

In [102]:
summ = positions.sum().sort_values(ascending=False)
result = summ.reset_index(name="Count")
result.columns = ["Position", "Total"]

print(f"third most popular position: {result["Total"][2]}")

result

third most popular position: 222

  Position  Total
0       OF    294
1       SP    227
2       RP    222
3       DH    134
4       3B    127
5       2B    125
6       1B    114
7        C    106
8       SS     85